# Generated by Django 6.0.1 on 2026-01-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customer_sign_options_customer_sign_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_sign',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer_sign',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer_sign',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_sign',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_sign',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_sign',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('user', 'User'), ('moderator', 'Moderator')], default='user', max_length=20),
        ),
    ]
